<html>
<head>
  <title>面向对象</title>
  <basefont face="宋体" size="2" />
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name="exporter-version" content="YXBJ Windows/600718 (zh-CN, DDL); Windows/10.0.0 (Win64);"/>
  <style>
    body, td {
      font-family: 宋体;
      font-size: 10pt;
    }
  </style>
</head>
<body>
<a name="550"/>
<h1>面向对象</h1>

<div>
<span><div>面向对象三大特性：</div><div>1、封装</div><div>    根据职责将属性和方法封装到一全抽象的类中</div><div>        定义类的准则</div><div>2、继承</div><div>    实现代码的重用，相同的代码不需要重复的编写</div><div>        设计类的技巧</div><div>        子类针对自己特有的需求，编写特定的代码</div><div>    python2中经典类是按深度优先来继承的，新式类是按广度优先来继承的</div><div>    python3中经典类和新式类都是统一按广度优先来继承的</div><div>3、多态</div><div>    不同的子类对象调用相同的父类方法，产生不同的执行结果</div><div>        多态可以增加代码的灵活度</div><div>        以继承和重写父类方法为前提</div><div>        是调用方法的技巧，不会影响到类的内部设计</div><div><br/></div><div><b>类</b></div><div>类方法和静态方法</div><div>1、类方法（@classmethod）</div><div>    类属性就是针对类对象定义的属性</div><div>        使用赋值语句在class关键字下方可以定义类属性</div><div>        类属性用于记录与这个类相关的特征</div><div>    类方法就是针对类对象定义的方法</div><div>        在类方法内部可以直接访问类属性或者调用其他的类方法</div><div>    语法如下：</div><div>        @classmethod</div><div>        def 类方法名(cls):</div><div>            pass</div><div>    类方法需要用修饰器@classmethod来标识，告诉解释器这是一个类方法</div><div>    类方法的第一个参数应该是cls</div><div>        由哪一个类调用的方法，方法内的cls就是哪一个类的引用</div><div>        这个参数和实例方法的第一个参数是self类似</div><div>        提示使用其他名称也可以，不过习惯使用cls</div><div>    通过类名.调用类方法，调用方法时，不需要传递cls参数</div><div>    在方法内部</div><div>        可以通过cls.访问类的属性</div><div>        也可以通过cls.调用其他的类方法</div><div>    在类方法内部，可以直接使用cls访问类属性或者调用类方法</div><div>2、静态方法（@staticmethod）</div><div>    在开发时，如果需要在类中封装一个方法，这个方法：</div><div>        既不需要访问实例属性或者调用实例方法</div><div>        也不需要访问类属性或者调用类方法</div><div>    在这个时候可以把这个方法封装成一个静态方法</div><div>    语法如下：</div><div>        @staticmethod</div><div>        def 静态方法名():</div><div>            pass</div><div>    静态方法需要用修饰器@staticmethod来标识，告诉解释器这是一个静态方法</div><div>    通过类名，调用静态方法</div><div>    </div><div><br/></div><div>    属性（@property）</div><div><span style="word-wrap: break-word; -webkit-nbsp-mode: space; -webkit-line-break: after-white-space;">        把一个方法变成一个静态属性</span></div><div><b>单例</b></div><div>    1、单例设计模式</div><div>        设计模式</div><div>            设计模式是前人工作的总结和提炼，通常，被人们广泛流传的设计模式都是针对某一特定问题的成熟的解决方案</div><div>            使用设计模式是为了可重用代码、让代码更容易被他人理解、保证代码可靠性</div><div>        单例设计模式</div><div>            目的--让类创建的对象，在系统中只有唯一的一个实例</div><div>            每一次执行类名()返回的对象，内存地址都是相同的</div><div>    单例设计模式的应用场景</div><div>        音乐播放 对象</div><div>        回收站 对象</div><div>        打印机 对象</div><div>        ......</div><div>    2、__new__方法</div><div>        使用类名()创建对象时，python的解释器首先会用__new__方法为对象分配空间</div><div>        __new__是一个由object基类提供的内置静态方法，主要作用有两个：</div><div>            1)在内存中为对象分配空间</div><div>            2)返回对象引用</div><div>        python的解释器获得对象的引用后，将引用作为第一个参数，传递给__init__方法</div><div>            重写__new__方法的代码非常固定</div><div>        重写__new__方法一定要return super().__new__(cls)</div><div>        否则python的解释器得不到分配了空间的对象引用，就不会调用对象的初始化方法</div><div>        注意：__new__是一个静态方法，在调用时需要主动传递cls参数</div><div><br/></div><div><br/></div><div><span style="word-wrap: break-word; -webkit-nbsp-mode: space; -webkit-line-break: after-white-space;">反射</span></div><div><span style="word-wrap: break-word; -webkit-nbsp-mode: space; -webkit-line-break: after-white-space;">    hasattr(obj, name_str)，判断一个对象里是否有对应的字符串的方法</span></div><div>    getattr(obj, name_str)，根据字符串去获取obj对象里的对应的方法</div><div>    setattr(obj, 'y', z)，等于&quot;obj.y = z&quot;</div><div>    delattr(obj, 'y')，删除属性&quot;obj.y&quot;</div><div>动态导入模块</div><div>    __import__()</div><div>    import importlib</div><div><br/></div><div><b>异常</b></div><div><span>    1、异常的概念</span><br/></div><div><span><span>    <span>    程序在运行时，如果python解释器遇到一个错误，会停止程序的执行，并且提示一些错误信息，这就是异常</span></span><br/></span></div><div><span><span>    <span>    程序停止执行并且提示错误信息这个动作，我们通常称之为：抛出(rasie)异常</span></span><br/></span></div><div><span><span>    <span>    程序开发时，很难将所有特殊的情况都处理的面面俱到，通过异常捕获可以针对突发事件做集中的处理，从而保证程序的稳定性和健壮性</span></span><br/></span></div><div>    2、捕获异常</div><div><span>    2.1简单的捕获异常语法</span></div><div><span><span>    <span>    在程序开发中，如果对某些代码的执行不能确定是否正确，可以增加try(尝试)来捕获异常</span></span><br/></span></div><div><span>    <span>    捕获异常最简单的语法格式：</span></span></div><div><span style="line-height: 1.45;"><span>    <span>    <span>    </span></span></span>try:</span><br/></div><div>        <span>    <span>    尝试执行的代码</span></span></div><div>    <span>    <span>    </span></span>except:</div><div>        <span>    <span>    出现错误的处理</span></span></div><div><span><span>    <span>    try尝试，下方编写要尝试代码，不确定是否能够正常执行的代码</span></span><br/></span></div><div><span>    <span>    except如果不是，下方编写尝试失败的代码</span></span></div><div><span><br/></span></div><div><span><span>    简单异常捕获演练--要求用户输入整数</span><br/></span></div><div><span>    <span>    try:</span></span><br/></div><div><span><span>    <span>    <span>    #提示用户输入一个数字</span></span></span><br/></span></div><div><span><span>    <span>    <span>    num = int(input(&quot;请输入数字：&quot;))</span></span></span><br/></span></div><div><span><span>    <span>    except:</span></span><br/></span></div><div><span><span>    <span>    <span>    print(&quot;请输入正确的数字&quot;)</span></span></span><br/></span></div><div>    2.2错误类型捕获</div><div><span>    <span>    在程序执行时，可能会遇到不同类型的异常，并且需要针对不同类型的异常，做出不同的响应，这个时候，就需要捕获错误类型了</span></span><br/></div><div><span><span>    <span>    语法如下：</span></span><br/></span></div><div><span>    <span>    <span>    </span></span></span><br/></div><div style="box-sizing: border-box; padding: 8px; font-family: Monaco, Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 12px; color: rgb(51, 51, 51); border-top-left-radius: 4px; border-top-right-radius: 4px; border-bottom-right-radius: 4px; border-bottom-left-radius: 4px; background-color: rgb(251, 250, 248); border: 1px solid rgba(0, 0, 0, 0.14902); background-position: initial initial; background-repeat: initial initial;-en-codeblock:true;"><div><span style="font-size: 9pt;"><span>    <span>    <span>    </span></span></span>try:</span></div><div><span style="font-size: 9pt;">                #尝试执行的代码</span></div><div><span style="font-size: 9pt;">                pass</span></div><div><span style="font-size: 9pt;">            except 错误类型1：</span></div><div><span style="font-size: 9pt;">                #针对错误类型1，对应的代码处理</span></div><div><span style="font-size: 9pt;">                pass</span></div><div><span style="font-size: 9pt;">            except (错误类型2，错误类型3):</span></div><div><span style="font-size: 9pt;">                #针对错误类型2和3，对应的代码处理</span></div><div><span style="font-size: 9pt;">                pass</span></div><div><span style="font-size: 9pt;">            execpt Exception as result:</span></div><div><span style="font-size: 9pt;">                print(&quot;未知错误 %s&quot; % result)</span></div></div><div><br/></div><div><span><span>    <span>    当python解释器抛出异常时，最后一行错误信息的第一个单词，就是错误类型</span></span><br/></span></div><div><span><br/></span></div><div><span><span>    <span>    异常类型捕获演练--要求用户输入整数</span></span><br/></span></div><div><span><span>    <span>    需求：</span></span><br/></span></div><div><span><span>    <span>    <span>    1.提示用户输入一个整数</span></span></span><br/></span></div><div><span><span>    <span>    <span>    2.使用8除以用户输入的整数并且输出</span></span></span><br/></span></div><div><span><span>    <span>    <span>    </span></span></span><br/></span></div><div><span>    <span>    <span>    </span></span></span><br/></div><div style="box-sizing: border-box; padding: 8px; font-family: Monaco, Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 12px; color: rgb(51, 51, 51); border-top-left-radius: 4px; border-top-right-radius: 4px; border-bottom-right-radius: 4px; border-bottom-left-radius: 4px; background-color: rgb(251, 250, 248); border: 1px solid rgba(0, 0, 0, 0.14902); background-position: initial initial; background-repeat: initial initial;-en-codeblock:true;"><div><span style="font-size: 9pt;"><span>    <span>    <span>    </span></span></span>try:</span></div><div><span style="font-size: 9pt;">                num = int(input(&quot;输入一个整数：&quot;))</span></div><div><span style="font-size: 9pt;">                result = 8 / num</span></div><div><span style="font-size: 9pt;">                print(result)</span></div><div><span style="font-size: 9pt;">            except ZeroDivisionError:</span></div><div><span style="font-size: 9pt;">                print(&quot;除数不能为0&quot;)</span></div><div><span style="font-size: 9pt;">            except ValueError:</span></div><div><span style="font-size: 9pt;">                print(&quot;请输入正确的整数&quot;)</span></div></div><div><br/></div><div><span><span>    <span>    </span></span><br/></span></div><div><span><span>    <span>    捕获未知错误</span></span><br/></span></div><div><span><span>    <span>    <span>    在开发时，要预判到所有可能出现的错误，还是有一定的难度的</span></span></span><br/></span></div><div><span><span>    <span>    <span>    如果希望程序无论出现任何错误，都不会因为python解释器抛出异常而被终止，可以再增加一个</span></span></span><br/></span></div><div><span><span>    <span>    <span>    <span>    except</span></span></span></span><br/></span></div><div><span><span>    <span>    <span>    语法如下：</span></span></span><br/></span></div><div><span><span>    <span>    <span>    <span>    except Excepiton as result:</span></span></span></span><br/></span></div><div><span>    <span>    <span>    <span>    <span>    print(&quot;未知错误 %s&quot; % result)</span></span></span></span></span></div><div><span><span>    2.3异常捕获完整语法</span><br/></span></div><div><span><span>    <span>    在实际开发中，为了能够处理复杂的异常情况，完整的异常语法如下：</span></span><br/></span></div><div><span>    <span>    </span></span><br/></div><div style="box-sizing: border-box; padding: 8px; font-family: Monaco, Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 12px; color: rgb(51, 51, 51); border-top-left-radius: 4px; border-top-right-radius: 4px; border-bottom-right-radius: 4px; border-bottom-left-radius: 4px; background-color: rgb(251, 250, 248); border: 1px solid rgba(0, 0, 0, 0.14902); background-position: initial initial; background-repeat: initial initial;-en-codeblock:true;"><div><span style="font-size: 9pt;"><span>    <span>    </span></span>try:</span></div><div><span style="font-size: 9pt;">            #尝试执行的代码</span></div><div><span style="font-size: 9pt;">            pass</span></div><div><span style="font-size: 9pt;">        except 错误类型1：</span></div><div><span style="font-size: 9pt;">            #针对错误类型1，对应的代码处理</span></div><div><span style="font-size: 9pt;">            pass</span></div><div><span style="font-size: 9pt;">        except (错误类型2):</span></div><div><span style="font-size: 9pt;">            #针对错误类型2，对应的代码处理</span></div><div><span style="font-size: 9pt;">            pass</span></div><div><span style="font-size: 9pt;">        except (错误类型3, 错误类型4):</span></div><div><span style="font-size: 9pt;">            #针对错误类型3和4，对应的代码处理</span></div><div><span style="font-size: 9pt;">            pass</span></div><div><span style="font-size: 9pt;">        except Exception as result:</span></div><div><span style="font-size: 9pt;">            #打印错误信息</span></div><div><span style="font-size: 9pt;">            print(result)</span></div><div><span style="font-size: 9pt;">        else:</span></div><div><span style="font-size: 9pt;">            #没有异常才会执行的代码</span></div><div><span style="font-size: 9pt;">            pass</span></div><div><span style="font-size: 9pt;">        finally:</span></div><div><span style="font-size: 9pt;">            #无论是否有异常，都会执行的代码</span></div><div><span style="font-size: 9pt;">            print(&quot;无论是否有异常，都会执行的代码&quot;)</span></div></div><div><br/></div><div><span>    <span>    else只有在没有异常时才会执行的代码</span></span></div><div><span>    <span>    finally无论是否有异常，都会执行代码</span></span></div><div><span>    <span>    之前一个演练的完整捕获异常的代码如下：</span></span></div><div><span>    3、异常的传递</span></div><div><span>    <span>    异常的传递--当函数/方法执行出现异常，会将异常传递给函数/方法的调用一方</span></span></div><div><span>    <span>    如果传递到主程序，仍然没有异常处理，程序才会被终止</span></span></div><div><span>    <span>    </span></span></div><div><span>    <span>    在开发中，可以在主函数中增加异常捕获</span></span></div><div><span>    <span>    而在主函数中调用的其他函数，只要出现异常，都会传递到主函数的异常捕获中</span></span></div><div><span>    <span>    这样就不需要在代码中，增加大量的异常捕获，能够保证代码的整洁</span></span></div><div><span>    <span>    </span></span></div><div><span>    <span>    需求：</span></span></div><div><span style="line-height: 1.45;"><span>    <span>    1.定义函数demo1()提示用户输入一个整数并且返回</span></span></span></div><div><span style="line-height: 1.45;"><span>    <span>    2.定义函数demo2()调用demo1()</span></span></span></div><div><span style="line-height: 1.45;"><span>    <span>    3.在主程序中调用demo2()</span></span></span></div><div><span style="line-height: 1.45;"><span>    <span>    <span>    </span></span></span></span><br/></div><div style="box-sizing: border-box; padding: 8px; font-family: Monaco, Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 12px; color: rgb(51, 51, 51); border-top-left-radius: 4px; border-top-right-radius: 4px; border-bottom-right-radius: 4px; border-bottom-left-radius: 4px; background-color: rgb(251, 250, 248); border: 1px solid rgba(0, 0, 0, 0.14902); background-position: initial initial; background-repeat: initial initial;-en-codeblock:true;"><div><span style="font-size: 9pt;">            def demo1():</span></div><div><span style="font-size: 9pt;">                return int(input(&quot;请输入一个整数：&quot;))</span></div><div><span style="font-size: 9pt;">            </span></div><div><span style="font-size: 9pt;">            def demo2():</span></div><div><span style="font-size: 9pt;">                return demo1()</span></div><div><span style="font-size: 9pt;">            </span></div><div><span style="font-size: 9pt;">            try:</span></div><div><span style="font-size: 9pt;">                print(demo2())</span></div><div><span style="font-size: 9pt;">            except VauleError:</span></div><div><span style="font-size: 9pt;">                print(&quot;请输入正确的整数&quot;)</span></div><div><span style="font-size: 9pt;">            except Exception as result:</span></div><div><span style="font-size: 9pt;">                print(&quot;未知错误 %s&quot; % result)</span></div></div><div><br/></div><div><span>    4、抛出raise异常</span><br/></div><div><span><span>    4.1应用场景</span><br/></span></div><div><span><span>    <span>    在开发中，除了代码执行出错python解释器会抛出异常之外</span></span><br/></span></div><div><span><span>    <span>    还可以根据应用程序特有的业务需求抛出异常</span></span><br/></span></div><div><span><span>    <span>   </span></span><br/></span></div><div><span><span>    4.2抛出异常</span><br/></span></div><div><span><span>    <span>    python中提供了一个Exception异常类</span></span><br/></span></div><div><span><span>    <span>    在开发时，如果满足特定业务需求时，希望抛出异常，可以：</span></span><br/></span></div><div><span><span>    <span>    <span>    1.创建一个Exception的对象</span></span></span><br/></span></div><div><span><span>    <span>    <span>    2.使用raise关键字抛出异常对象</span></span></span><br/></span></div><div><span><span>    <span>    </span></span><br/></span></div><div><span><span>    <span>    需求：</span></span><br/></span></div><div><span><span>    <span>    <span>    定义input_password，提示用户输入密码</span></span></span><br/></span></div><div><span><span>    <span>    <span>    如果用户输入长度&lt;8，抛出异常</span></span></span><br/></span></div><div><span><span>    <span>    <span>    如果用户输入长度&gt;=8，返回输入密码</span></span></span><br/></span></div><div>断言（assert）</div><div>    </div><div><br/></div><div><br/></div><div><br/></div><div><br/></div><div><br/></div></span>
</div></body></html> 